# important meta data
dataset_name: alipay
neg_sample: 20
vocabulary_size: 695323 
uid_col: uid
iid_col: iid
ufeat_cols: []
ifeat_cols: [cid, sid]
user_num_fields: 1
item_num_fields: 3
num_fields: 4
label_col: ranking
test_list_len: 30

# dataset directory and file names
# input data for Dataset
data_dir: data/alipay/feateng_data
train_inter: data/alipay/feateng_data/train.inter
unpv_inter: data/alipay/feateng_data/unpv.inter
test_inter: data/alipay/feateng_data/test.inter
user_df: data/alipay/feateng_data/feat.user
item_df: data/alipay/feateng_data/feat.item

# have_hist: True
# hist_dict: data/alipay/feateng_data/hist_dict.pkl
# hist_len_dict: data/alipay/feateng_data/hist_len_dict.pkl

# filtered_item_dict: data/alipay/feateng_data/filtered_iids.pkl
# filtered_user_dict: data/alipay/feateng_data/filtered_uids.pkl
